-- MySQL Script generated by MySQL Workbench
-- Thu Oct  7 15:52:48 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema- -----------------------------------------------------
-- CREATE SCHEMA IF NOT EXISTS DEFAULT CHARACTER SET utf8 ;
-- USE ;
-- drop schema
-- -----------------------------------------------------
-- Table `dificuldade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dificuldade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assunto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assunto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pergunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pergunta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `questao` VARCHAR(200),
  `resposta1` VARCHAR(100),
  `resposta2` VARCHAR(100),
  `resposta3` VARCHAR(100),
  `resposta4` VARCHAR(100),
  `dificuldade_id` INT,
  `assunto_id` INT ,
  PRIMARY KEY (`id`),
  INDEX `fk_pergunta_dificuldade_idx` (`dificuldade_id` ASC) ,
  INDEX `fk_pergunta_assunto1_idx` (`assunto_id` ASC) ,
  CONSTRAINT `fk_pergunta_dificuldade`
    FOREIGN KEY (`dificuldade_id`)
    REFERENCES `dificuldade` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pergunta_assunto1`
    FOREIGN KEY (`assunto_id`)
    REFERENCES `assunto` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jogador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jogador` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `ativo` CHAR(1) NOT NULL,
  `logado` CHAR(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jogo` (
  `id` INT NOT NULL,
  `data_hora_inicio` DATETIME NULL,
  `data_hora_termino` DATETIME NULL,
  `jogador_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_jogo_jogador1_idx` (`jogador_id` ASC) ,
  CONSTRAINT `fk_jogo_jogador1`
    FOREIGN KEY (`jogador_id`)
    REFERENCES `jogador` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prova`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prova` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sessao` VARCHAR(200) NULL,
  `qtde_acertos` INT NULL,
  `jogador_id` INT NOT NULL,
  `jogo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_prova_jogador1_idx` (`jogador_id` ASC) ,
  INDEX `fk_prova_jogo1_idx` (`jogo_id` ASC) ,
  CONSTRAINT `fk_prova_jogador1`
    FOREIGN KEY (`jogador_id`)
    REFERENCES `jogador` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_prova_jogo1`
    FOREIGN KEY (`jogo_id`)
    REFERENCES `jogo` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rel_prova_pergunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rel_prova_pergunta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pergunta_id` INT NULL,
  `prova_id` INT NULL,
  `num_questao_na_prova` VARCHAR(45) NULL,
  `resposta_certa` CHAR(1) NULL,
  INDEX `fk_rel_prova_aluno_pergunta1_idx` (`pergunta_id` ASC) ,
  INDEX `fk_rel_prova_aluno_prova1_idx` (`prova_id` ASC) ,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_rel_prova_aluno_pergunta1`
    FOREIGN KEY (`pergunta_id`)
    REFERENCES `pergunta` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_rel_prova_aluno_prova1`
    FOREIGN KEY (`prova_id`)
    REFERENCES `prova` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resposta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resposta` (
  `id` INT NOT NULL,
  `resposta_aluno` CHAR(1) NULL,
  `rel_prova_pergunta_id` INT NULL,
  `jogador_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_resposta_rel_prova_pergunta1_idx` (`rel_prova_pergunta_id` ASC) ,
  INDEX `fk_resposta_jogador1_idx` (`jogador_id` ASC) ,
  CONSTRAINT `fk_resposta_rel_prova_pergunta1`
    FOREIGN KEY (`rel_prova_pergunta_id`)
    REFERENCES `rel_prova_pergunta` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_resposta_jogador1`
    FOREIGN KEY (`jogador_id`)
    REFERENCES `jogador` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `historico_login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `historico_login` (
  `id` INT NOT NULL,
  `data_hora_login` DATETIME NULL,
  `data_hora_logout` DATETIME NULL,
  `jogador_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_historico_login_jogador1_idx` (`jogador_id` ASC) ,
  CONSTRAINT `fk_historico_login_jogador1`
    FOREIGN KEY (`jogador_id`)
    REFERENCES `jogador` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
